### ISSUE TITLE
TypeError:setValue(self,int): argument 1 has unexpected type 'float

### ISSUE THREAD

**Issue by BlackCatte** [SockHungryClutz/KritaVFX#3]
Hey there, ever since upgrading from Krita 4 to 5, I've been getting this error that makes using the plugin impossible.. I get this error whenever I try clicking any of the plugins in this VFX pack from the menu:

TypeError
Python 3.10.2: /usr/bin/python3
Mon Feb 21 09:23:32 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/me/.local/share/krita/pykrita/VFX/VFX.py in ChromaticAberrationWindow(self=<VFX.VFX.VFX object>)
   14         self.settings = QSettings(configPath + '/krita-scripterrc', QSettings.IniFormat)
   15         self.uiController = UIController.UIController()
   16         self.uiController.initialize(self, "CA")
   17 
   18     def BloomWindow(self):
self = <VFX.VFX.VFX object>
self.uiController = <VFX.UIController.UIController object>
self.uiController.initialize = <bound method UIController.initialize of <VFX.UIController.UIController object>>

 /home/me/.local/share/krita/pykrita/VFX/UIController.py in initialize(self=<VFX.UIController.UIController object>, parent=<VFX.VFX.VFX object>, widgetType='CA')
   56         vbox.addWidget(self.buttonBox)
   57 
   58         self.readSettings()
   59 
   60         self.mainWidget.setWindowTitle("VFX - " + self.filterWidget.getWindowName())
self = <VFX.UIController.UIController object>
self.readSettings = <bound method UIController.readSettings of <VFX.UIController.UIController object>>

 /home/me/.local/share/krita/pykrita/VFX/UIController.py in readSettings(self=<VFX.UIController.UIController object>)
   91     def readSettings(self):
   92         rect = self.parent.settings.value("geometry", QRect(600, 200, 400, 200))
   93         self.mainWidget.setGeometry(rect)
   94         if self.filterWidget:
   95             self.filterWidget.readSettings(self.parent.settings)
self = <VFX.UIController.UIController object>
self.filterWidget = <VFX.ChromaticAberrationWidget.ChromAbWidget object>
self.filterWidget.readSettings = <bound method ChromAbWidget.readSettings of <VFX.ChromaticAberrationWidget.ChromAbWidget object>>
self.parent = <VFX.VFX.VFX object>
self.parent.settings = <PyQt5.QtCore.QSettings object>

 /home/me/.local/share/krita/pykrita/VFX/ChromaticAberrationWidget.py in readSettings(self=<VFX.ChromaticAberrationWidget.ChromAbWidget object>, settings=<PyQt5.QtCore.QSettings object>)
  192         self.shapeBtn1.setChecked(self.isShapeRadial)
  193         self.shapeBtn2.setChecked(not self.isShapeRadial)
  194         self.maxDisplace.setValue(self.maxD * 1000)
  195         self.foBtn1.setChecked(self.isFalloffExp)
  196         self.foBtn2.setChecked(not self.isFalloffExp)
self = <VFX.ChromaticAberrationWidget.ChromAbWidget object>
self.maxDisplace = <PyQt5.QtWidgets.QSlider object>
self.maxDisplace.setValue = <built-in method setValue of QSlider object>
self.maxD = 0.01
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("setValue(self, int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/me/.local/share/krita/pykrita/VFX/VFX.py", line 16, in ChromaticAberrationWindow
    self.uiController.initialize(self, "CA")
  File "/home/me/.local/share/krita/pykrita/VFX/UIController.py", line 58, in initialize
    self.readSettings()
  File "/home/me/.local/share/krita/pykrita/VFX/UIController.py", line 95, in readSettings
    self.filterWidget.readSettings(self.parent.settings)
  File "/home/me/.local/share/krita/pykrita/VFX/ChromaticAberrationWidget.py", line 194, in readSettings
    self.maxDisplace.setValue(self.maxD * 1000)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by SockHungryClutz** [comment]
Thanks for reporting this error. Looks like an edge case with rounding the float value. I'll have a fix for this over the weekend, as well as a couple other things that I've been waiting to push :)

**Comment by SockHungryClutz** [comment]
Nevermind about this weekend, decided to do it now since it's a quick fix. Please see the latest release for the fix!
https://github.com/SockHungryClutz/KritaVFX/releases/tag/v0.1.1

And please do let me know if this does not solve your issue!
